app:
  name: Yusuf's blog
  description: Just a simple blog
  bottom: Yusuf's microblog. All content is unlicensed.
  admin_password: $2a$14$pAk/G7qYWHQpBSAwNWiUHOc1DirDxeXf53BYqvh6hMQGztgM.AeWm
server:
  addr: 0.0.0.0:80
  hostname: localhost:5000
postgres:
  addr: microblog-postgres:5432
  db: microblog_db
  user: user
  password: user
  ssl_mode: disable
